### ISSUE TITLE
How to work with a socket?

### ISSUE THREAD

**Issue by DoradoV** [cmark0v/p0f-json#1]
Good afternoon. How to work with a socket?
I run: /p0f -i ens3 -j -s p0f-socket -d
I try to use the standard tool, nothing.
./p0f-client /opt/p0f-JSON/p0f-socket <IP_address>
[-] PROGRAM ABORT : Short read from API socket.
          Location : main(), p0f-client.c:134

**Comment by cmark0v** [comment]
this code is a slightly modified version of p0f that spits json out of stdout. i didnt work on the socket feature and im not sure if it works properly in the original(also not sure if i broke it when i did my modifications). i didnt have good luck with it when trying to use it, but i wasnt using that client either (p0f-client.c)
